[project]
name = "venv"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "streamlit",
    "kagglehub",
    "jupyter>=1.1.1",
    "ipykernel>=7.3.0",
]

[project.optional-dependencies]

[project.scripts]
train = "src.training.train:main"
"src.training.train" = "src.training.train:main"

cpu = [
    "tensorflow-cpu",
]

cuda = [
    "tensorflow[and-cuda]",
]
